name: pr

on:
  pull_request:
    branches:
      - master
      - beta

env:
  CI: "true"
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:+UseParallelGC -Xmx3g -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=512M"
  GRADLE_CACHE_LOCAL: true
  GRADLE_CACHE_REMOTE: true
  GRADLE_CACHE_PUSH: true
  GRADLE_CACHE_USERNAME: apikey
  GRADLE_CACHE_PASSWORD: ${{ secrets.BUILDLESS_APIKEY }}
  CACHE_ENDPOINT: https://gradle.less.build/cache/generic/
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  TEST_EXCEPTIONS: true

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest, windows-latest-8-cores, ubuntu-latest-4-cores]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Cache packages
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          path: |
            ~/.sonar/cache
            ~/.konan
            ~/.gradle/caches
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '19'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: "Build and Test"
        uses: gradle/gradle-build-action@v2
        id: gradlebuild
        with:
          cache-read-only: false
          arguments: |
            preMerge
            --scan
            --no-daemon
            --warning-mode=none
            --dependency-verification=lenient
            -Pci=true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
